
export const FETCH_CHARACTER = "FETCH_CHARACTER";
export const PENDING_CHARACTER = "PENDING_CHARACTER"; 
export const CHARACTER_REJECT = "CHARACTER_REJECT";

export const FETCH_SINGLECHARACTER = "FETCH_SINGLECHARACTER";
export const PENDING_SINGLECHARACTER = "PENDING_SINGLECHARACTER"; 
export const SINGLECHARACTER_REJECT = "CHARACTER_REJECT";
export const CHANGE_PARAMS = "CHANGE_PARAMS";
export const LOAD_MORE_DATA = "LOAD_MORE_DATA";
